#!/bin/bash
awk '
/^    private JPanel createCard/ {
    print "    private void showAddStudentDialog() {"
    print "        JDialog dialog = new JDialog(this, \"Ajouter un Étudiant\", true);"
    print "        dialog.setSize(400, 450);"
    print "        dialog.setLocationRelativeTo(this);"
    print "        dialog.getContentPane().setBackground(bgDark);"
    print ""
    print "        JPanel panel = new JPanel(new GridLayout(8, 2, 10, 10));"
    print "        panel.setBackground(bgDark);"
    print "        panel.setBorder(new EmptyBorder(20, 20, 20, 20));"
    print ""
    print "        JLabel lblId = new JLabel(\"ID unique :\"); lblId.setForeground(textPrimary);"
    print "        JTextField txtId = new JTextField();"
    print "        JLabel lblMatricule = new JLabel(\"Matricule :\"); lblMatricule.setForeground(textPrimary);"
    print "        JTextField txtMatricule = new JTextField();"
    print "        JLabel lblNom = new JLabel(\"Nom :\"); lblNom.setForeground(textPrimary);"
    print "        JTextField txtNom = new JTextField();"
    print "        JLabel lblPrenom = new JLabel(\"Prénom :\"); lblPrenom.setForeground(textPrimary);"
    print "        JTextField txtPrenom = new JTextField();"
    print "        JLabel lblEmail = new JLabel(\"Email :\"); lblEmail.setForeground(textPrimary);"
    print "        JTextField txtEmail = new JTextField();"
    print "        JLabel lblFiliere = new JLabel(\"Filière :\"); lblFiliere.setForeground(textPrimary);"
    print "        JTextField txtFiliere = new JTextField();"
    print "        JLabel lblAnnee = new JLabel(\"Année (ex: L3) :\"); lblAnnee.setForeground(textPrimary);"
    print "        JTextField txtAnnee = new JTextField();"
    print ""
    print "        JButton btnSubmit = new JButton(\"Enregistrer\");"
    print "        btnSubmit.setBackground(accentGold);"
    print "        btnSubmit.setForeground(bgDark);"
    print "        btnSubmit.setFont(new Font(\"Segoe UI\", Font.BOLD, 14));"
    print ""
    print "        btnSubmit.addActionListener(e -> {"
    print "            try {"
    print "                Etudiant nouveau = new Etudiant(txtId.getText(), txtNom.getText(), txtPrenom.getText(),"
    print "                        txtEmail.getText(), LocalDate.now(), txtMatricule.getText(), txtAnnee.getText(), txtFiliere.getText());"
    print "                gestionActeurs.ajouterPersonne(nouveau);"
    print "                refreshStudentsTable();"
    print "                refreshDashboardStats();"
    print "                dialog.dispose();"
    print "            } catch (Exception ex) {"
    print "                JOptionPane.showMessageDialog(dialog, \"Veuillez remplir correctement les champs.\", \"Erreur\", JOptionPane.ERROR_MESSAGE);"
    print "            }"
    print "        });"
    print ""
    print "        panel.add(lblId); panel.add(txtId);"
    print "        panel.add(lblMatricule); panel.add(txtMatricule);"
    print "        panel.add(lblNom); panel.add(txtNom);"
    print "        panel.add(lblPrenom); panel.add(txtPrenom);"
    print "        panel.add(lblEmail); panel.add(txtEmail);"
    print "        panel.add(lblFiliere); panel.add(txtFiliere);"
    print "        panel.add(lblAnnee); panel.add(txtAnnee);"
    print "        panel.add(new JLabel(\"\")); panel.add(btnSubmit);"
    print ""
    print "        dialog.add(panel);"
    print "        dialog.setVisible(true);"
    print "    }"
    print ""
    print $0
    next
}
{ print }
' src/com/campusconnect/ui/DashboardGUI.java > temp.java && mv temp.java src/com/campusconnect/ui/DashboardGUI.java
